# Generated by Django 5.2 on 2025-04-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custompermission',
            name='codename',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
