# Generated by Django 5.2 on 2025-04-09 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userManage', '0002_user_is_staff_user_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
    ]
