# Generated by Django 5.2 on 2025-04-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internshipManage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='total_working_days',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
    ]
