# Generated by Django 5.2 on 2025-04-16 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internshipManage', '0002_internship_total_working_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='total_working_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
