# Generated by Django 5.2 on 2025-04-21 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internshipManage', '0003_alter_internship_total_working_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipdiary',
            name='tasks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internshipdiary',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
