version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: redis_cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - app_network

  web:
    build: .
    container_name: django_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - logs:/app/logs
    working_dir: /app
    environment:
      - PYTHONPATH=/app
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    restart: always
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - app_network

  cron:
    build: .
    container_name: django_cron
    volumes:
      - .:/app
      - logs:/app/logs
    working_dir: /app
    environment:
      - PYTHONPATH=/app
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: >
      bash -c "apt-get update && apt-get install -y cron && 
      service cron start && 
      python manage.py crontab add && 
      tail -f /dev/null"
    depends_on:
      - web
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  redis_data:
    name: redis_data
  logs:
    name: app_logs
